### ISSUE TITLE
Klassendiagramm auf aktuellen main-Stand bringen

### ISSUE THREAD

**Issue by JavaRacing1** [JavaRacing1/BA-INT-Online-Game#10]
Das Klassendiagramm enthält bisher nur die grobe Klassenstruktur mit Beschreibungen, Attribute und Methoden fehlen meist noch. Die aktuell implementierten Klassen können daher schonmal mit ins Diagramm übernommen werden.

**Comment by JavaRacing1** [comment]
Aktueller Stand Diagramm: db1b01bad6c7a4491b4e6f293332a342a47c1cf4

**Comment by R4z0rb3ard** [comment]
Für eine extra Klasse / Szene zur Auswahl der Figuren würde ich mir wie in unserem Tower-Defense-Spiel die Funktionalität der Turmauswahl vorstellen: ein Auswahlfeld, wo maximal 16 Figuren (für 4 Spieler sollten wirs soweit bringen wollen mit dem Spiel) in einem Auswahl Container dem Spieler zur Auswahl geben, und wenn eine Figur ausgewählt wurde für andere Spieler nicht mehr auswählbar ist (Statusbool oder Flag was das mit angibt). Ein Designe für so eine Szene kann ich elementar schon einmal mit vorbereiten

**Comment by JavaRacing1** [comment]
> Für die MultiplayerLobbyScreen Klasse oder dem MultiplayerConnectionScreen, so wie ich das verstehe ist darin die Auswahl der Spielfiguren und der Teamfarben, etc. bestimmt möglich, oder? 

Der MultiplayerConnectionScreen soll rein zur Verbindung mit einem Server dienen. Dort kann man auch seinen Nutzernamen setzen. Alle Einstellungen zum Spiel werden dann im MultiplayerLobbyScreen getroffen. Dort kann der Hoster Einstellungen für den Levelgenerator als auch für allgemeine Spieloptionen (z.B. Rundenzeit, Anzahl Charaktere pro Spieler, etc.) treffen. Im selben Screen kann jeder Spieler dann seine Charaktere auswählen. Inwiefern das dann direkt auf dem Screen selbst oder mit Pop-ups ermöglicht wird, müssen wir dann beim Design sehen.

**Comment by JavaRacing1** [comment]
> wenn eine Figur ausgewählt wurde für andere Spieler nicht mehr auswählbar ist (Statusbool oder Flag was das mit angibt)

Ich weiß nicht, ob das so eine gute Idee ist. Wenn jede Figur tatsächlich andere Boni/Fähigkeiten haben soll, ist der schnellste Spieler dann im Vorteil, während der letzte Spieler, der die Lobby beitritt, keine freie Charakterwahl mehr hat und dadurch benachteiligt wird. 

Ich würde das Thema sowie die Screens später in einem separaten Ticket diskutieren, das gehört nicht mit hier hinein. Ich würde damit auch erstmal warten, bis ich mit der Levelgenerierung so gut wie fertig bin. Dann haben wir nämlich eine Grundlage für einen Sandbox-Modus, wo wir diesbezüglich viel experimentieren und testen können.

**Comment by R4z0rb3ard** [comment]
Also wollten wir immer noch Charaktere mit Boni/ Fähigkeiten (also in Klassen eingeteilt) erstellen. Da kann ich also meine Figuren, die ich erstellen will, an so basic Eigenschaften wie "mehr Leben = Metall Designe oder dicker/ mehr Rüstung", "agiler als normal = weniger bis keine Rüstung, magische Effekte am Körper" oder "mehr Schaden austeilen aus normal = Waffengürtel, Rucksack mit Werkzeug, Cyborg halb Mensch halb Maschine" etc.  anpassen

**Comment by JavaRacing1** [comment]
Aktueller Stand vom Diagramm: 33f19359

**Comment by JavaRacing1** [comment]
Aktueller Stand vom Diagramm: c27f0c13

Wird mit in die main-Branche gemergt

**Comment by JavaRacing1** [comment]
Aktueller Stand vom Diagramm: 47152ddf
