### ISSUE TITLE
Grundfunktionalität der Spielerbewegung einbauen

### ISSUE THREAD

**Issue by JavaRacing1** [JavaRacing1/BA-INT-Online-Game#11]
Der Spieler ist eine Kernkomponente des Spiels und besitzt ein paar unterschiedliche Bewegungstypen. Da sich diese in Zukunft noch erweitern könnten, soll das System auf einer **State-Machine** basieren. Die notwendigen States sowie die grobe Klassenstruktur können in der Branch **diagrams** unter **/diagrams** gefunden werden. 

Eine Beispiel-Implementation einer State-Machine kann [hier](https://www.gdquest.com/tutorial/godot/design-patterns/finite-state-machine/) gefunden werden

**Comment by R4z0rb3ard** [comment]
Die Spielfigurenbewegung werde ich mit in der erstellten Branch "PlayerMovementAndSpriteAnimation" erstellen (siehe Beitrag mit den Designe der Spielfiguren)
