### ISSUE TITLE
Hauptmenü designen

### ISSUE THREAD

**Issue by JavaRacing1** [JavaRacing1/BA-INT-Online-Game#7]
Das Hauptmenü ist funktionstechnisch schon zum Großteil implementiert, besitzt aber noch kein Design. 

Folgende Buttons muss das Hauptmenü enthalten:
- Spielen → Popup mit folgenden Button-Optionen: Multiplayer, Sandbox, Tutorial
- Einstellungen
- Erfolge
- Credits
- Beenden

Die Buttons können entweder als Hintergrundtextur mit ausgeschriebenen Text oder als Icons ohne Text erstellt werden, es muss nur zum Erscheinungsbild passen

**Comment by JavaRacing1** [comment]
Noch vergessen: Der Button im Credit-Overlay muss auch noch vom Aussehen her angepasst werden

**Comment by R4z0rb3ard** [comment]
Wer von uns 3 Leuten (Jonas, Fabian, DJ) soll die grafische Gestaltung mit übernehmen? hatten wir jetzt schon eine grobe Design Idee gehabt für die Schriftart, die Buttons und auch allgemein für die Textboxen und Hintergründe? Direkt vom Borderlands/ Fallout/ etc. Grafikstil irgendwas 1 zu 1 nachzupixeln wäre denk ich nicht gut. Wir sollten dafür ein Meeting mal ansetzen, wo jeder mal ein paar Beispiele an Texturen oder Zeichnungen ausn Internet oder selber gemacht den anderen zeigen kann

**Comment by JavaRacing1** [comment]
Ja, sowas müssen wir in einem Meeting besprechen. Wir hatten jetzt noch keine wirklichen Design-Ideen für Buttons oder Hintergründe. Bei der Schrift werden wir wahrscheinlich eine Pixel-Schrift benutzen müssen, da es sonst mit der niedrigen Auflösung eine Unschärfe geben kann.

**Comment by R4z0rb3ard** [comment]
Okay für die Schrift könnte ich was vorbereiten und vielleicht selber gestallten. Wie groß glaubst du muss die Schrift wegen der allgemeinen Spielgröße sein.  Ich bereite auf jeden Fall schon etwas vor für ein baldiges Meeting zum zeigen
