### ISSUE TITLE
Einstellungsmenü designen

### ISSUE THREAD

**Issue by JavaRacing1** [JavaRacing1/BA-INT-Online-Game#8]
Das Einstellungsmenü hat bisher nur das standardmäßige Aussehen, eine Anpassung ist daher auch hier notwendig.

Die 4 Kategorien (Grafik, Audio, Steuerung und Gameplay) sind bisher in der Mitte aneinander zusammengepfercht, am besten sollten sie sich vom linken bis zum rechten Bildschirmrand erstrecken.

Nach #6 benötigen wir zusätzlich zu Labels und Buttons noch Designs für folgende Node-Typen:
- OptionButton
- CheckButton
- HSlider

**Comment by R4z0rb3ard** [comment]
genau die selbe Frage wie fürs Hauptmenü. Wer von uns 3 Leuten solls machen zu gestallten und vielleicht auch noch technische Switch_Szenen Funktionen oder Buttoun Ereignisse (was noch gebraucht wird) umsetzten.
